services:
  frontend:
    build:
      context: ../
      dockerfile: docker/frontend
    image: frontend-demo
    #container_name: frontend-demo-container
    ports:
      - "80:80"
      - "443:443"
    networks:
      - ems-demo-docker-network
    environment:
      - ELASTICSEARCH_URL=http://host.docker.internal:9201
      - SPRING_DATASOURCE_URL=jdbc:mysql://172.31.88.27:3306/invoice
    volumes:
      - /etc/letsencrypt/live/emp.pathbreakertech.in/fullchain.pem:/etc/ssl/certs/server.crt:ro
      - /etc/letsencrypt/live/emp.pathbreakertech.in/privkey.pem:/etc/ssl/private/server.key:ro
      # Add this if using dhparam
      - /etc/letsencrypt/ssl-dhparams.pem:/etc/ssl/dhparam.pem:ro
      - ems_produpload_files:/home/ubuntu/ems_prod_imag_bkp/

  identity:
    build:
      context: ../
      dockerfile: docker/identity
    image: identity-demo
    #container_name: identity-demo-container
    ports:
      - "9002:9002"
    networks:
      - ems-demo-docker-network
    environment:
      - ELASTICSEARCH_URL=http://host.docker.internal:9201
      - SPRING_DATASOURCE_URL=jdbc:mysql://172.31.88.27:3306/invoice
    volumes:
      - ems_produpload_files:/home/ubuntu/ems_prod_imag_bkp/

  employee:
    build:
      context: ../
      dockerfile: docker/employee
    image: employee-demo
    #container_name: employee-demo-container
    ports:
      - "8012:8012"
    networks:
      - ems-demo-docker-network
    environment:
      - ELASTICSEARCH_URL=http://host.docker.internal:9201
      - SPRING_DATASOURCE_URL=jdbc:mysql://172.31.88.27:3306/invoice
    volumes:
      - ems_produpload_files:/home/ubuntu/ems_prod_imag_bkp/

  invoice:
    build:
      context: ../
      dockerfile: docker/invoice
    image: invoice-demo
    #container_name: invoice-demo-container
    ports:
      - "8002:8002"
    networks:
      - ems-demo-docker-network
    environment:
      - ELASTICSEARCH_URL=http://host.docker.internal:9201
      - SPRING_DATASOURCE_URL=jdbc:mysql://172.31.88.27:3306/invoice
    volumes:
      - ems_produpload_files:/home/ubuntu/ems_prod_imag_bkp/

networks:
  ems-demo-docker-network:

volumes:
  ems_produpload_files:

