version: '3.8'

services:
  frontend:
    build:
      context: ./ui/src/
      dockerfile: docker/FrontendDockerfile
    ports:
      - "3000:3000"
    networks:
      - my-network

  identity:
    build:
      context: ./identity
      dockerfile: docker/IdentityModuleDockerfile
    ports:
      - "9090:2800"
    networks:
      - my-network

  employee:
    build:
      context: ./employee
      dockerfile: docker/EmployeeModuleDockerfile
    ports:
      - "8092:8092"
    networks:
      - my-network

networks:
  my-network:
    external: true
