version: '3.8'

services:
  frontend:
    build:
      context: /var/lib/jenkins/workspace/ems-deployement/ui/
      dockerfile: /var/lib/jenkins/workspace/ems-deployement/docker/FrontendDockerfile
    ports:
      - "3000:3000"
    networks:
      - my-network

  identity:
    build:
      context: /var/lib/jenkins/workspace/ems-deployement/identity/
      dockerfile: /var/lib/jenkins/workspace/ems-deployement/docker/IdentityModuleDockerfile
    ports:
      - "9090:2800"
    networks:
      - my-network

  employee:
    build:
      context: /var/lib/jenkins/workspace/ems-deployement/employee
      dockerfile: /var/lib/jenkins/workspace/ems-deployement/docker/EmployeeModuleDockerfile
    ports:
      - "8092:8092"
    networks:
      - my-network

networks:
  my-network:
    external: true
