
services:
  frontend:
    build:
      context: /var/lib/jenkins/workspace/ems-deployement/docker/frontend
      dockerfile: frontend
    ports:
      - "2800:3000"
    networks:
      - ems-network
    environment:
      - ELASTICSEARCH_URL=http://host.docker.internal:9200

  identity:
    build:
      context: /var/lib/jenkins/workspace/ems-deployement/docker/identity
      dockerfile: identity
    ports:
      - "9090:9090"
    networks:
      - ems-network
    environment:
      - ELASTICSEARCH_URL=http://host.docker.internal:9200

  employee:
    build:
      context: /var/lib/jenkins/workspace/ems-deployement/docker/employee
      dockerfile: employee
    ports:
      - "8092:8092"
    networks:
      - ems-network
    environment:
      - ELASTICSEARCH_URL=http://host.docker.internal:9200

networks:
  ems-network:
