version: '3.8'

services:
  employee:
    build:
      context: .
      dockerfile: docker/EmployeeModuleDockerfile
    ports:
      - "8092:8092"
    networks:
      - app-network

  identity:
    build:
      context: .
      dockerfile: docker/IdentityModuleDockerfile
    ports:
      - "9090:9090"
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: docker/FrontendDockerfile
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
