server:
  port: 9002
  servlet:
    contextPath: /ems
  ssl:
    enabled: true
    key-store: /opt/EMS-demo/certificates/keystore.jks
    key-store-password: pathbreaker
    key-alias: ems.pathbreakertech.in
    key-store-type: JKS
spring:
  aop:
    proxy-target-class: true
  main:
    allow-circular-references: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: pbtjava@gmail.com
    password: jcnsrxqjifkrvqxl
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 2GB
      max-request-size: 2GB
  thymeleaf:
    cache: false
  security:
    basic:
      enabled: false

fixed:
  otp: 123456

es:
  esHost: localhost
  esPort: 9201
springdoc:
  swagger-ui:
    tagsSorter: alpha
    path: /swagger-ui
  api-docs:
    resolve-schema-properties: true
    path: /api-docs
