server:
  port: 8002
  servlet:
    contextPath: /invoice
  ssl:
    enabled: true
    key-store: ../certificates/ssl.jks
    key-store-password: pathbreaker
    key-alias: pbt
    key-store-type: JKS
# MySQL Database Configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/invoice
    username: root
    password: Path@2014
    driver-class-name: com.mysql.cj.jdbc.Driver
  # Hibernate Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
# Swagger API Documentation
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
